import { defineConfig } from 'orval'

export default defineConfig({
  api: {
    input: {
      target: process.env.API_DOCS_URL || 'http://localhost:8000/docs/api.json'
    },
    output: {
      target: './lib/api/generated',
      client: 'fetch',
      mode: 'single',
      override: {
        fetch: {
          includeHttpStatusReturnType: false
        },
        header: () => [
          '// @ts-nocheck',
          'Generated by orval',
          'Do not edit manually.'
        ]
      }
    }
  }
})
