apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: residential-management-dev
  labels:
    app.kubernetes.io/name: residential-management
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app.kubernetes.io/name: residential-management
    app.kubernetes.io/component: backend
