apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: residential-management-dev
  labels:
    app.kubernetes.io/name: residential-management
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      name: http
  selector:
    app.kubernetes.io/name: residential-management
    app.kubernetes.io/component: frontend
