apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: residential-management-dev
type: Opaque
stringData:
  APP_KEY: ${APP_KEY}
  DB_PASSWORD: ${DB_PASSWORD}
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  AWS_ENDPOINT: ${AWS_ENDPOINT}
  MAIL_USERNAME: ${MAIL_USERNAME}
  MAIL_PASSWORD: ${MAIL_PASSWORD}
