import type {
  CommissionConfigListProjects200,
  CommissionConfigShowConfig200,
  CommissionConfigSaveConfig200,
  CommissionConfigSaveAdjusters200,
  SaveCommissionAdjusterRequest
} from '#api/generated/laravel'

// Re-export Orval types used by components/pages
export type { CommissionProjectListResource } from '#api/generated/laravel'
export type {
  CommissionConfigDetailResource,
  CommissionConfigDetailResourcePlatform,
  CommissionConfigDetailResourcePartyRulesItem,
  CommissionConfigDetailResourceDeptRulesItem,
  CommissionConfigDetailResourceDeptRulesItemStaffRulesItem
} from '#api/generated/laravel'

// ─── Types not generated by Orval (raw JSON endpoint) ───

export interface AvailableDepartmentAccount {
  id: number
  name: string
  employee_code: string | null
}

export interface AvailableDepartment {
  id: number
  name: string
  accounts: AvailableDepartmentAccount[]
}

interface AvailableDepartmentsResponse {
  success: boolean
  data: AvailableDepartment[]
}

// ─── Value types ───

export type CommissionValueType = 'percent' | 'fixed' | 'both'
export type CommissionPartyType = 'operating_company' | 'board_of_directors' | 'management'

// ─── Form state types (FE-only, no BE equivalent) ───

export interface PartyRuleForm {
  party_type: CommissionPartyType
  label: string
  value_type: CommissionValueType
  percent: number | null
  value_fixed: number | null
}

export interface StaffRuleForm {
  account_id: number
  account_name: string
  employee_code: string | null
  selected: boolean
  sort_order: number
  value_type: CommissionValueType
  percent: number | null
  value_fixed: number | null
}

export interface DeptRuleForm {
  department_id: number
  department_name: string
  selected: boolean
  sort_order: number
  value_type: CommissionValueType
  percent: number | null
  value_fixed: number | null
  expanded: boolean
  staff_rules: StaffRuleForm[]
}

// ─── API request type (manual, not Orval) ───

interface SaveCommissionConfigPayload {
  party_rules: {
    party_type: CommissionPartyType
    value_type: CommissionValueType
    percent: number | null
    value_fixed: number | null
  }[]
  dept_rules?: {
    department_id: number
    sort_order: number
    value_type: CommissionValueType
    percent: number | null
    value_fixed: number | null
    staff_rules: {
      account_id: number
      sort_order: number
      value_type: CommissionValueType
      percent: number | null
      value_fixed: number | null
    }[]
  }[]
}

// ─── Constants ───

export const COMMISSION_VALUE_TYPE_OPTIONS = [
  { label: 'Phần trăm', value: 'percent' as CommissionValueType },
  { label: 'Tiền cứng', value: 'fixed' as CommissionValueType },
  { label: 'Cả hai', value: 'both' as CommissionValueType }
]

export const COMMISSION_PARTY_LABELS: Record<CommissionPartyType, string> = {
  operating_company: 'Công ty vận hành',
  board_of_directors: 'Ban quản trị',
  management: 'Ban quản lý'
}

/** Fixed deduction order for all configurable parties */
export const COMMISSION_PARTY_ORDER: CommissionPartyType[] = [
  'operating_company',
  'board_of_directors',
  'management'
]

export function commissionValueTypeLabel(value: string): string {
  return COMMISSION_VALUE_TYPE_OPTIONS.find(o => o.value === value)?.label ?? value
}

// ─── Queries ───

export function useCommissionProjects() {
  return useApiFetch<CommissionConfigListProjects200>('/pmc/commission/projects')
}

export function useCommissionConfig(projectId: MaybeRefOrGetter<number>) {
  return useApiFetch<CommissionConfigShowConfig200>(
    computed(() => `/pmc/commission/projects/${toValue(projectId)}`),
    { watch: [() => toValue(projectId)] }
  )
}

export function useAvailableDepartments(projectId: MaybeRefOrGetter<number>) {
  return useApiFetch<AvailableDepartmentsResponse>(
    computed(() => `/pmc/commission/projects/${toValue(projectId)}/available-departments`),
    { watch: [() => toValue(projectId)] }
  )
}

// ─── Mutations ───

export function apiSaveCommissionConfig(projectId: number, data: SaveCommissionConfigPayload) {
  return $api<CommissionConfigSaveConfig200>(`/pmc/commission/projects/${projectId}`, {
    method: 'PUT',
    body: data
  })
}

export function apiSaveCommissionAdjusters(projectId: number, data: SaveCommissionAdjusterRequest) {
  return $api<CommissionConfigSaveAdjusters200>(`/pmc/commission/projects/${projectId}/adjusters`, {
    method: 'PUT',
    body: data
  })
}
