apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: residential-management-prod
  labels:
    app.kubernetes.io/name: residential-management
    app.kubernetes.io/component: backend
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081
      name: http
  selector:
    app.kubernetes.io/name: residential-management
    app.kubernetes.io/component: backend
